#!/bin/bash
#
# Configure a machine to build openfoam
#

IMPI_EXE=
if [ $# -eq 2 -a "$2" = "--accept-eula" ] ; then
	IMPI_EXE="$1"
else
	echo "Usage: $0 IMPI_EXE_PATH --accept-eula" 1>&2
	exit 1
fi

if [ "$USER" != "root" ] ; then
	echo "$0 must be run as root" 1>&2
	exit 1
fi

chmod +x "$IMPI_EXE"
"$IMPI_EXE" -a -s -c --eula accept --install-dir /opt/intel || exit 1

yum groupinstall -y "Development Tools" || exit 1
yum install -y qt-devel PyQt4-devel curl-devel bzip2-devel xz-devel mpfr-devel qt5-qttools-devel gnuplot qt5-qtx11extras-devel libXt-devel readline-devel ncurses-devel cmake3 tmux freeglut-devel webkitgtk4 webkitgtk4-devel fftw fftw-devel pigz || exit 1
update-alternatives --install /usr/bin/cmake cmake "$(which cmake3)" 1 || exit 1


