#!/bin/bash
# --------------------------------------------------------------------------- #
#   ==   ===  ==                                                              #
#  ||   ||=  || ))  support s. r. o. 2014, www.cfdsupport.com                 #
#   ==        ==                                                              #
# --------------------------------------------------------------------------- #

# This script will duplicate the template directory A320-case-stationary.org
# to A320-case-stationary and run the steady-state case inside the newly
# created directory.

# check OpenFOAM environment
if [[ $(echo $WM_PROJECT_VERSION | cut -c1-3) != "dev" ]] && [[ $(echo $WM_PROJECT_VERSION | cut -c1-3) != "7" ]]
then
    echo "Use OpenFOAM 7 or OpenFOAM dev with this example script, please."
    exit
fi

# create new A320-case-stationary directory from template (does not overwrite existing files)
cp -rnT A320-case-stationary.org A320-case-stationary


# run the stationary case
cd A320-case-stationary
time ./runSolver
cd ../
