#!/bin/bash
# --------------------------------------------------------------------------- #
#   ==   ===  ==                                                              #
#  ||   ||=  || ))  support s. r. o. 2014, www.cfdsupport.com                 #
#   ==        ==                                                              #
# --------------------------------------------------------------------------- #

# This script will delete the mesh and case directories
#      A320-mesh
#      A320-case-stationary
#      A320-case-transient

echo " 1. Cleaning mesh."
rm -rf A320-mesh

echo " 2. Cleaning stationary case."
rm -rf A320-case-stationary

echo " 3. Cleaning transient case."
rm -rf A320-case-transient
