#!/bin/bash
# --------------------------------------------------------------------------- #
#   ==   ===  ==                                                              #
#  ||   ||=  || ))  support s. r. o. 2014, www.cfdsupport.com                 #
#   ==  ||    ==                                                              #
# --------------------------------------------------------------------------- #

echo

./Allclean

echo

./1-makeMesh

echo

./2-runStationaryCase

echo

./3-runTransientCase

echo