#!/bin/bash
#
# Copyright (c)2020 System Fabric Works, Inc.
#
# Uses concepts from CFD Support A320.
#

cd ${0%/*} || exit 1    # Run from this directory

if [ -z "$SUBDOMAINS" ] ; then
       SUBDOMAINS="$(nproc)"
fi

if [ -z "$WM_PROJECT_DIR" ] ; then
    echo "OpenFOAM environment not set" 1>&2
    exit 1
fi

if [ -d motorBike-solve ] ; then
    echo "motorBike-solve already exists" 1>&2
    exit 1
fi
if [  ! -d motorBike-mesh ] ; then
    echo "motorBike-mesh does not exist" 1>&2
    exit 1
fi

cp -rnT motorBike.org motorBike-solve
cp -r motorBike-mesh/constant motorBike-solve/

cd motorBike-solve || exit 1
time ./Allrun -s solve -n $SUBDOMAINS
exit $?
